### ISSUE TITLE
SocketError(getaddrinfo: Temporary failure in name resolution)

### ISSUE THREAD

**Issue by kdankert** [realtarget/traefik2-docker-stack#3]
I am currently setting up gitlab on my server using your traefik configuration from GitHub. Although I encounter a problem with my smtp configuration, I am not able to send emails. 

I would like to send an email using Office 365 I purchased from GoDaddy.com. My domain and server is hosted there as well. Unfortunately of I use the settings from https://docs.gitlab.com/omnibus/settings/smtp.html#office365 I get an error in gitlab when I try to send the email using the Notify cmd in the gitlab rails console.

SocketError(getaddrinfo: Temporary failure in name resolution)

I couldn't find any solutions on the internet. 

docker-compose.yml
```yaml
version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    command: --api.insecure=true --providers.docker -log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gitlab:
    image: gitlab/gitlab-ee:latest
    restart: always
    healthcheck:
      disable: true
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.*domain*'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.office365.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = "*email*"
        gitlab_rails['smtp_password'] = "*password*"
        gitlab_rails['smtp_domain'] = "*domain*"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = 'gitlab@*domain*'
        gitlab_rails['gitlab_email_reply_to'] = 'noreply@*domain*'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.http.services.gitlab_xerocscom.loadbalancer.server.port=80
      - traefik.http.routers.gitlab.service=gitlab_xerocscom
      - traefik.http.routers.gitlab.rule=Host(`gitlab.*domain*`)
```

Note: 
The server is running on http only so far. In addition to that it is not possible to access gitlab by ssh yet.

**Comment by kdankert** [comment]
I kinda fixed this problem. This was a problem with invalid dns setup in my host. Although i still have a problem. None of my internet traffic does get redirected back from the web over the eth0 interface to the docker0 interface to the container.

**Comment by realtarget** [comment]
Hi Kjell,
sorry for the late answer. Did you define the network in your docker-compose?

```
services:
  # The GitLab container itself
  gitlab:
     networks:
      - traefik-proxy
      - default
```

and 

```
networks:
  traefik-proxy:
    external: true

```

Can you see all your networks in `docker network ls`?

**Comment by kdankert** [comment]
This is not only specific to the docker-compose file

When i traceroute 8.8.8.8 in the docker container I get:
traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 46 byte packets
 1  172.17.0.1 (172.17.0.1)  0.017 ms  0.004 ms  0.003 ms
 2  10.197.159.253 (10.197.159.253)  0.252 ms  0.209 ms  0.184 ms
 3  10.253.98.3 (10.253.98.3)  0.235 ms  10.253.98.0 (10.253.98.0)  0.267 ms  10.253.98.1 (10.253.98.1)  0.247 ms
 4  10.253.98.7 (10.253.98.7)  0.233 ms  10.253.98.6 (10.253.98.6)  0.263 ms  10.253.98.4 (10.253.98.4)  0.272 ms
 5  10.253.1.3 (10.253.1.3)  0.233 ms  0.173 ms  10.253.1.2 (10.253.1.2)  0.210 ms
 6  10.242.134.68 (10.242.134.68)  0.254 ms  10.242.134.76 (10.242.134.76)  0.316 ms  10.242.134.68 (10.242.134.68)  0.235 ms
 7  188.121.32.148 (188.121.32.148)  0.447 ms  188.121.32.102 (188.121.32.102)  0.500 ms  188.121.32.100 (188.121.32.100)  1.392 ms
 8  ae3.ibrsa0105-01.ams3.bb.godaddy.com (188.121.32.6)  2.080 ms  0.715 ms  0.553 ms
 9  *  *  *

Although it should look more like this using --net=host except the first call is obviously missing
traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 46 byte packets
 1  10.197.159.253 (10.197.159.253)  0.399 ms  0.269 ms  0.209 ms
 2  10.253.98.2 (10.253.98.2)  0.315 ms  0.285 ms  10.253.98.3 (10.253.98.3)  0.302 ms
 3  10.253.98.7 (10.253.98.7)  0.324 ms  10.253.98.6 (10.253.98.6)  0.221 ms  10.253.98.5 (10.253.98.5)  0.191 ms
 4  10.253.1.3 (10.253.1.3)  0.228 ms  10.253.1.2 (10.253.1.2)  0.273 ms  0.246 ms
 5  10.242.134.76 (10.242.134.76)  0.287 ms  0.206 ms  0.227 ms
 6  188.121.32.102 (188.121.32.102)  0.443 ms  188.121.32.148 (188.121.32.148)  0.525 ms  188.121.32.142 (188.121.32.142)  0.703 ms
 7  ae3.ibrsa0105-01.ams3.bb.godaddy.com (188.121.32.6)  0.615 ms  ae2.ibrsa0105-01.ams3.bb.godaddy.com (188.121.32.4)  0.427 ms  ae3.ibrsa0105-01.ams3.bb.godaddy.com (188.121.32.6)  0.367 ms
 8  core1.ams.net.google.com (80.249.208.247)  1.162 ms  1.052 ms  1.182 ms
 9  108.170.241.193 (108.170.241.193)  1.314 ms  108.170.241.161 (108.170.241.161)  2.139 ms  1.860 ms
10  108.170.236.223 (108.170.236.223)  1.127 ms  108.170.236.135 (108.170.236.135)  1.434 ms  172.253.66.185 (172.253.66.185)  2.005 ms
11  dns.google (8.8.8.8)  1.339 ms  1.374 ms  1.102 ms

**Comment by kdankert** [comment]
The weird part is that I am able to access 188.121.32.6 in both calls, but it suddenly stops after that when bridge network is used

**Comment by realtarget** [comment]
What's the output of `docker network ls`?

**Comment by kdankert** [comment]
This is the output of `docker network ls`. Right now I am only concerned about the non working bridge, thats why i haven't setup the docker compose file.

NETWORK ID          NAME                DRIVER              SCOPE
9e53daac9dfa        bridge              bridge              local
90f1a04ee410        host                host                local
174ce2acdce7        none                null                local

Output of `docker network inspect bridge`
[
    {
        "Name": "bridge",
        "Id": "9e53daac9dfab85860461affd94cff05fd9acb4bc803255ae9255876126c2102",
        "Created": "2019-10-01T12:17:50.342266492-07:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

**Comment by realtarget** [comment]
Can you please try adding this to your docker-compose.yml?

```
services:
  # The GitLab container itself
  gitlab:
     (...)
     networks:
      - bridge
      - default
```

And at the end of the file:

```
networks:
  bridge:
    external: true

```
